### ISSUE TITLE
Developing Idea / Scheduling User Testing

### ISSUE THREAD

**Issue by MichaelGoff** [NCSU-SE-Spring-17/SE-17-S#1]
Hey guys, we really need to get a move on with developing this idea and moving on to some user testing ideas and actually booking that room. Could you reiterate the idea here for the sake of recording our conversations in Github?

**Comment by bhaskarsinha1311** [comment]
Central Idea: A web application in which a user can log on and look up people with a particular skill set and invite them to collaborate on a particular project.

**Comment by MichaelGoff** [comment]
Alright so does anyone have any relevant papers or existing code-bases we can modify or extend to accomplish this task in 3 different ways?

Secondary question: Any initial ideas for users testing / interviews relating to forming teams or finding team members with particular skills?

**Comment by bhaskarsinha1311** [comment]
I found the below paper which has some ideas on how to match people.
https://www.google.com/patents/US5963951
I am still looking into some other papers to find something useful, haven't searched for any existing code bases.

**Comment by sshankjha** [comment]
http://delivery.acm.org.prox.lib.ncsu.edu/10.1145/1100000/1096740/p401-terveen.pdf?ip=152.14.136.96&id=1096740&acc=ACTIVE%20SERVICE&key=6ABC8B4C00F6EE47%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&CFID=720059291&CFTOKEN=36493159&__acm__=1485217322_185ac41302e0f125b3b32bc24e519b7c

I found one excellent paper (link above) relating to social matching. Lil old (1990) and lil long (35 pages) but I will try to summarize it:
Two types of movie matching discussed at the start, which we can modify and use in our case maybe?
1. Collaborative filtering technique matches a target user with other users who have similar preferences, and then recommends items that these neighboring users rated highly and that the target user has not rated. (Peer review based?)
2.  Content-based recommenders locate items that are similar to those a user has liked in the past. (Skills based?)

**Comment by sshankjha** [comment]
Similarly, matches can be done on the basis of similar interest, proximity, complementary/supplementary skill sets, common friends (referal type), etc. We can create google forms based on these to find out what all to people consider before deciding on group partners.

**Comment by sshankjha** [comment]
Shall we meet today (just before class) or tomorrow?

**Comment by MichaelGoff** [comment]
Just before class works for me.

**Comment by jdeng8** [comment]
at what time?

**Comment by MichaelGoff** [comment]
What will we be discussing at this meeting?

**Comment by jdeng8** [comment]
I think the most important things are data collection(evaluate) and conduct research. We can discuss how and what to do with surveys and interviews to collect data. Then we can find papers relative to our project after the meeting.

**Comment by MichaelGoff** [comment]
Okay. I think it is important to find existing code bases as well so we don't have to reinvent the wheel here.

**Comment by MichaelGoff** [comment]
What time is everyone available? I'm at the library from now until class starts

**Comment by bhaskarsinha1311** [comment]
I am also in the library from now until class starts. I can meet @3.30.

**Comment by jdeng8** [comment]
ok, I will be there before 3:30.

**Comment by MichaelGoff** [comment]
I will be there at 3:30 as well. Where should we meet


----
Michael Goff
Graduate Student Computer Science
North Carolina State University

**Comment by MichaelGoff** [comment]
I have found a table on the 4th floor at the top of the stairs

**Comment by bhaskarsinha1311** [comment]
Cool, I'll meet you there in 20 mins.
