### ISSUE TITLE
Finalizing milestones

### ISSUE THREAD

**Issue by sshankjha** [NCSU-SE-Spring-17/SE-17-S#10]
We have to come with milestones before tomorrow's class so let us note down as many things as possible which needs to be done. Will create milestones according to discussion below.

- Pull skills from LinkedIn (LinkedIn API?)
- Signup page details (what all information are we taking from user and which all will be pulled from other sites)
- Anything else which is needed for more than 1 project design?
- Project 1 design
       a. Threshold?
       b. Search result display?
- Project 2 design
       a. How will professor/manager add all the students/employers details?
- Project 3 design
       a. How to implement lottery?

- Testing should start around Feb 24/25.

**Comment by MichaelGoff** [comment]
These look good for different categories. I think we could even create these as milestones on github issues. From that point we could break down some of these into various issues and then add more issues to each milestone as they come. 

I would suggest adding as a milestone

- Coming with a stack for our application
- Implementing a skeleton application

**Comment by jdeng8** [comment]
We should also design evaluation method. Professor has mentioned about that several times. We can discuss with him tomorrow.

**Comment by sshankjha** [comment]
Does not that come under March milestone?

**Comment by jdeng8** [comment]
Are the data all extract from LinkedIn?  So that we don't need to maintain a database.
I am not sure when to do the evaluation, maybe later.

**Comment by sshankjha** [comment]
I think we should maintain separate database as well. In LinkedIn, I only add those skills which I am totally confident about. But that might not be the case while doing projects. So I would prefer (as a end user) to add skills besides LinkedIn one as well.

**Comment by sshankjha** [comment]
So most important things **(CORE)** mentioned till now:
1. LinkedIn API
2. Signup/login page
3. Database?

**Comment by sshankjha** [comment]
I have created 4 issues for implementing core and three approaches. Added them in milestones as well. But I think we have change structure of milestones.
Rather than having monthly milestones, it would be better if we have milestones like: "Finalize designs" due by Feb 12/13, "implement and test approaches" by feb 25. 
So let me know how you all want to proceed.

**Comment by MichaelGoff** [comment]
Agreed. I think the new milestones are good. Everything looks good to me. Perhaps we can start laying out future issues as well to populate the other milestones but this seems like an organized start to me.
