### ISSUE TITLE
Once a week meeting

### ISSUE THREAD

**Issue by sshankjha** [NCSU-SE-Spring-17/SE-17-S#11]
Since we will be working separately on our assigned issues, I was thinking that we should meet once a week (or more?) to see how well we are progressing. Half an hour or an hour should be enough. So at what time will you guys be free? Comment below! 

MW - 2nd half
TTF - 1st half 

P.S.: We need to more often for first week to decide on 3 approaches's design.

**Comment by jdeng8** [comment]
I am free at the above time slides

**Comment by jdeng8** [comment]
MW-2nd half
TT - all day before SE class
F- all day

**Comment by MichaelGoff** [comment]
TT after SE class (Would much prefer these days)
F - All day

**Comment by bhaskarsinha1311** [comment]
TT before or after class and Friday all day.

**Comment by sshankjha** [comment]
We can meet before/after class for 5-10 mins. If not enough , Friday 11.30-12.30. I ll book one room in library accordingly.

**Comment by sshankjha** [comment]
Alright. Friday 11.30-12.30. I ll send meeting invitation on Thursday to confirm.
