### ISSUE TITLE
Design: core

### ISSUE THREAD

**Issue by sshankjha** [NCSU-SE-Spring-17/SE-17-S#12]
Following are core/common to all approaches so need to get these done first.

- [x] Finalize the login/signup page (what all details will we ask from end user?)
- [ ] LinkedIn API (pull skill set for particular profile)
- [x] Database design (how to save profile details)
- [x] Database hosting?
- [x] Designing the web app
- [ ] Logging

**Comment by MichaelGoff** [comment]
Angular seems like the way to go to quickly start up a webapp. There are plenty of options to use as a starting point which allows us to hit the ground running. We can use LinkedIn API for authentication. I'm sure we will need some kind of DB but I'm not sure what we will use for that as of yet.

**Comment by MichaelGoff** [comment]
Potential alternative to Angular. Using Node.js and Express with mongoDB to store data. 

http://cwbuecheler.com/web/tutorials/2014/restful-web-app-node-express-mongodb/

Here is a quick tutorial on how it all works.

**Comment by sshankjha** [comment]
LinkedIn API and logging will be added to add-ons. Closing the issue.
