### ISSUE TITLE
Create 3 branches of our repo. 1 for each approach

### ISSUE THREAD

**Issue by MichaelGoff** [NCSU-SE-Spring-17/SE-17-S#17]

**Comment by sshankjha** [comment]
- [ ] Approach 2 branch creation
- [ ] Approach 3 branch creation

@MichaelGoff @jdeng8 Can you close this issue when you have created respective repos?

**Comment by MichaelGoff** [comment]
Like I said in the title we should make 3 branches on this repo so everything is in one place

I thought @bhaskarsinha1311 said he was going to do this on Slack.

**Comment by sshankjha** [comment]
He has created repo for approach 1. You guys can create one when we are done with creating the core.

**Comment by MichaelGoff** [comment]
I know, I'm saying we should make it a branch on this repo instead so everything is in one place for submission purposes.

**Comment by sshankjha** [comment]
Oh yes. I think it will be better to use one single repo.

**Comment by sshankjha** [comment]
So I am updating my first comment. Close this issue when branches have been created.
