### ISSUE TITLE
Update group info

### ISSUE THREAD

**Issue by sshankjha** [NCSU-SE-Spring-17/SE-17-S#2]
Few minor things which needs to be updated:
1. Github name (Its group T now, not group S)
I think only @bhaskarsinha1311  can do it as he was the one who starter this group.
2. Update the link in se17 google sheet. One link is already present but it is for old S group.

**Comment by MichaelGoff** [comment]
The link will have to be updated after @bhaskarsinha1311 changes the repo name since it will change the URL of the repo
