### ISSUE TITLE
Sort the users into teams

### ISSUE THREAD

**Issue by MichaelGoff** [NCSU-SE-Spring-17/SE-17-S#24]
Backend work to actually sort these users

**Comment by sshankjha** [comment]
Initial approach pushed. Though divided team is only shown in console for now. Will complete database writing after tomorrow's exam.

**Comment by MichaelGoff** [comment]
You know our demo is tomorrow right? We need to have this part live by
then.

----
Michael Goff
Graduate Student Computer Science
North Carolina State University

**Comment by sshankjha** [comment]
Done.

**Comment by MichaelGoff** [comment]
Awesome. Could you start doing some tests for your functionality?

----
Michael Goff
Graduate Student Computer Science
North Carolina State University
