### ISSUE TITLE
Meeting 1/24/17

### ISSUE THREAD

**Issue by MichaelGoff** [NCSU-SE-Spring-17/SE-17-S#3]
- Google form survey would work best
- Are you a master's student?
- Do you have problems finding team members with specific skill sets?
- How often are your teams successful 1-5
- How many different team projects do you work on in a year?
    - 1 - 3
    - 4 - 6
    - 7+ 
- What have you done to find those team members?
- Chit #? (if applicable)
- Which services have you used to form teams before?
    - LinkedIn
    - Class Forums
    - Slack
    - In person
    - Other
- What experiences did you have with those team members which you found. 
- What were some problems that you had with team members in the past?
- In general, which is better for you?
    - Assigned teams
    - Freely formed teams
- Rate the following services 1 -5: 
    - Slack
    - LinkedIn
    - 
- What are the factors do you think contribute to you finding a team aside from their technical expertise?
- Do you prefer to collaborate online or in person with your team?
- Do you prefer to start a team or join a pre-existing team?
- How often do you asses a potential team members skills before forming a team?
- If there was [Potential application here] would you find it helpful?
    - yes / maybe / no
- How often would you use it during team creation?
    - Often
    - Sometimes 
    - etc
- What would make it more convenient for you to find team members?

# Side Notes
- Team could put out job postings and people could apply
- meet-up app / website
- meet-ups like python meets or something
- similar to dating apps in a way
- Areas of expertise to assess
    - Front-end
    - Security
    - etc
- people could both apply to a team or be in an eligible pool 
- LinkedIn API log in or Google log in
- How much can we reuse across designs. 
- quantitative way to assess social connections, things they like and shared connections on linked in.

**Comment by MichaelGoff** [comment]
Approaches:

1. User creates a group and requests people to apply
2. Groups automatically created based on population's traits.
3. Users have a list of preferred projects and application sorts people into groups based on preferences

**Comment by bhaskarsinha1311** [comment]
Guys, I have sent the quiz, please take a look at it and see if any changes need to be made.

**Comment by timm** [comment]
just a suggestion, but...

![image](https://cloud.githubusercontent.com/assets/29195/22345550/80f6dcd4-e3ce-11e6-8dc1-1c787aaabb39.png)
