### ISSUE TITLE
Need to figure out how to get skills from Google users

### ISSUE THREAD

**Issue by MichaelGoff** [NCSU-SE-Spring-17/SE-17-S#34]
When a google user logs in we need to find a way to get their skills since they bypass the usual sign in page.

**Comment by sshankjha** [comment]
@MichaelGoff We can add separate page for adding skills. So first page will be for signing up (either google or email), then add/edit skills page and lastly user's home page.

**Comment by sshankjha** [comment]
@MichaelGoff Need clarification here. You are talking about sign up process right? Because there is only one sign in option.

**Comment by MichaelGoff** [comment]
Yeah need skills for Google users on sign up. We already have a sign up
page for email users. You can login through either Google or email after
the fact

**Comment by sshankjha** [comment]
![signuppage](https://cloud.githubusercontent.com/assets/23535378/23389464/1b0b63be-fd36-11e6-8005-7e7d0ed21dbd.PNG)

There is only single option.

**Comment by sshankjha** [comment]
The other is login page which has option of email and google.

**Comment by MichaelGoff** [comment]
The login with Google button will automatically sign a user up if they
don't have an account

On Mon, Feb 27, 2017, 21:47 Shashank Jha <notifications@github.com> wrote:

The other is login page which has option of email and google.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NCSU-SE-Spring-17/SE-17-S/issues/34#issuecomment-282925718>,
or mute the thread

**Comment by sshankjha** [comment]
Pushed the correction.
