### ISSUE TITLE
Change title bar/header for user home page

### ISSUE THREAD

**Issue by sshankjha** [NCSU-SE-Spring-17/SE-17-S#37]
We have too many placeholders in user's home page right now. I am removing unnecessary ones.
It will only have:

1. App's name
2. Home (User's home)
3. Profiles -> edit profile and log out (drop down)

@bhaskarsinha1311 Do we need anything else?

**Comment by bhaskarsinha1311** [comment]
No, I think that's enough.

**Comment by sshankjha** [comment]
Pushed the updated code.
