### ISSUE TITLE
Software Report

### ISSUE THREAD

**Issue by MichaelGoff** [NCSU-SE-Spring-17/SE-17-S#38]
We need to write a 3 page report 1 page for each approach to turn in with the project.

**Comment by MichaelGoff** [comment]
Due Tuesday

**Comment by MichaelGoff** [comment]
I have created a folder in master that has the February paper inside. Can you guys write about your sections? We are aiming for 1 full page per section. We are using the same Sharelatex document for writing. Let me know if you can't access it. Remember this is due tomorrow!

**Comment by sshankjha** [comment]
@MichaelGoff Can you mention about generating team function as well. That is yet to properly implemented and tested. Not sure if that falls under 'roadblock' category or 'doing/yet to be done'. But I think that is worth mentioning.

**Comment by MichaelGoff** [comment]
Okay you can write a bit about it if you want.
