### ISSUE TITLE
Evaluation method discussion

### ISSUE THREAD

**Issue by jdeng8** [NCSU-SE-Spring-17/SE-17-S#46]
Let's post our ideas and discuss the evaluation method here

**Comment by sshankjha** [comment]
Approach2:
- Create 9 chit with skills in it. Each representing a person. Ask someone to make groups of 3 with equally distributed skills. Note down the time.
- Next time, add 6 more chits. Again ask to divide into groups evenly. Note down the time. 
- Lastly, add 6 more chits. Same process. 
- At the end, note when it becomes exponentially hard to divide. 
- In the end, show how it can be done using our app. 
- Compare both approaches and ask user how s/he rates our app in terms of usefulness (after showing that dividing the team evenly for more than 15-20 person is really really hard).

**Comment by sshankjha** [comment]
Approach1:
- Ask if users know of any app/site which provides searching of users based on 'skill' criteria. (I think this is more of google form type of question).

**Comment by jdeng8** [comment]
So what's the criterion to evaluate how good is each method?
I agree that user's experience is one criterion of evaluation

**Comment by sshankjha** [comment]
We need to discuss about report/ppt as well. So shall we continue in same issue or create new one?

**Comment by bhaskarsinha1311** [comment]
Create new Issue
