### ISSUE TITLE
Report / ppt discussion

### ISSUE THREAD

**Issue by MichaelGoff** [NCSU-SE-Spring-17/SE-17-S#47]
Report is to be 6 pages

ppt between 6 and 12 minutes any format you wish.

**Comment by sshankjha** [comment]
March milestone is due on 31st March. Ppt/report is due on April 7th.

**Comment by MichaelGoff** [comment]
I would prefer to not present again. How should we structure this paper?

**Comment by MichaelGoff** [comment]
If we each write a little more than a page and a half we can meet the length requirement no problem. Here is an outline of sections I think we will need upon looking at sample papers. 

- Intro
- Experiment
    - Task methodology
- Results
- Discussion 
    - Observations / Limitations
- Best Approach
- Future Work
- Conclusion

**Comment by MichaelGoff** [comment]
I think experiment and results sections will be best to split by approach. Discussion and observations might merge them.

**Comment by bhaskarsinha1311** [comment]
So I would recommend everyone to write briefly about the responses to their approaches today and we can do the combined part after the evaluations are done tomorrow.

**Comment by MichaelGoff** [comment]
Results might be swayed by additional responses you get tomorrow though. Without finalizing the collected data I think we can only really talk about how we framed the experiment and the expected results right now. We cannot draw conclusions without complete data.

**Comment by MichaelGoff** [comment]
Maybe some future work as well

**Comment by bhaskarsinha1311** [comment]
Okay so we can start with the Intro and the Task Methodology and results we can do tomorrow.

**Comment by MichaelGoff** [comment]
Okay, I am at work right now, can you set up a shareLatex doc for us to contribute to?

**Comment by MichaelGoff** [comment]
I will set up a sharelatex doc to contribute to

**Comment by bhaskarsinha1311** [comment]
Sure, I'll do that by 5, stuck in an assignment.

**Comment by bhaskarsinha1311** [comment]
Cool!

**Comment by MichaelGoff** [comment]
The doc has been set up. You can find it at the same place as the last two papers.

**Comment by MichaelGoff** [comment]
BTW the latex doc is here. Let me know if you don't have access. I think everyone can still edit this:

https://www.sharelatex.com/project/588a782f19b669f77a7d39bd
