### ISSUE TITLE
Aggregate Papers here:

### ISSUE THREAD

**Issue by MichaelGoff** [NCSU-SE-Spring-17/SE-17-S#5]
Hey guys, aggregate any papers you have come across and code bases here so we have a list to reference while we write this paper.

**Comment by bhaskarsinha1311** [comment]
Computerized on-line dating service for searching and matching people 
https://www.google.com/patents/US5963951

**Comment by bhaskarsinha1311** [comment]
Social Matching: A Framework and Research Agenda

**Comment by bhaskarsinha1311** [comment]
I have got these two so far. I can look into more and start with the slides.

**Comment by jdeng8** [comment]
I found a paper research about software project resources and team member allocate:
The use of Search-Based Optimization Techniques to Schedule and Staff Software Projects: an Approach and an Empirical Study - Massimiliano Di Penta
The author use search-based software engineering to design team allocation algorithm
