### ISSUE TITLE
Everyone paste your email here

### ISSUE THREAD

**Issue by MichaelGoff** [NCSU-SE-Spring-17/SE-17-S#7]
Hey I need everyone's email to share the latex file with you to edit. Paste below. Thanks!

magoff2@ncsu.edu

**Comment by bhaskarsinha1311** [comment]
bsinha@ncsu.edu

**Comment by jdeng8** [comment]
jdeng8@ncsu.edu

**Comment by sshankjha** [comment]
sjha5@ncsu.edu

**Comment by MichaelGoff** [comment]
Thanks!
