### ISSUE TITLE
Everyone can access?

### ISSUE THREAD

**Issue by MichaelGoff** [NCSU-SE-Spring-17/SE-17-S#8]
Just want to confirm that everyone can access and edit the latex document on sharelatex.

I have started doing some writing about the survey questions and I will soon write about the responses.

**Comment by sshankjha** [comment]
Just added my name in the pdf. So yes, I can access and edit it!

**Comment by MichaelGoff** [comment]
What other sections can you guys write? I know we need to talk about research and that sort of thing. We also need to outline the three solutions

**Comment by bhaskarsinha1311** [comment]
Should we get together once, to discuss the deliverables and the outlines of the solutions.

**Comment by MichaelGoff** [comment]
Approaches:

1. User creates a group and requests people to apply
2. Groups automatically created based on population's traits.
3. Users have a list of preferred projects and application sorts people into groups based on preferences

I don't really have time to get together this weekend. We can approach these as we discussed with the professor. I don't think these proposals have to be super in depth detail wise just an outline of what they will do. At least that's what it looks like from the other papers. It didn't look like they even had 3 solutions to their problems either. 

- I think the paper just needs to be 5 pages and we can model them after the other examples
    - The papers in question are under the January heading here: https://github.com/txt/se17/blob/master/doc/project.md
- I believe the slides will just be the auto paced 20 slides 20 seconds per slide and I believe I recall the professor saying just 1 speaker would be appropriate and other speakers will come in on other presentations.
