### ISSUE TITLE
Parts of paper that need done.

### ISSUE THREAD

**Issue by MichaelGoff** [NCSU-SE-Spring-17/SE-17-S#9]
- [x] Abstract
- [x] Introduction
- [x] Outline Survey
- [x] graphs
- [x] free responses
- [x] Approach 1
- [x] Approach 2
- [x] Approach 3
- [x] Research Ties
- [x] Conclusion

Here are the parts that need to be done in the paper still. I wrote about the survey questions and the graph related answers in the survey. I didn't really address the free response questions. I will be stepping away for a little while but I will be glad to come back and do some editing when the time comes. We are at about 4 pages now give or take a page from placeholder text.

**Comment by sshankjha** [comment]
Can somebody do approach 3? I am willing to do approach 1 and 2 but would be great if I could see what exactly needs to be written first.

**Comment by sshankjha** [comment]
@MichaelGoff Can you cover introduction as well?
@jdeng8 You have to write about approach 3, research ties and conclusion.
I will be doing free responses, approach 1 and 2. 
So we all have 3 topics each to cover.
@bhaskarsinha1311 is taking care of ppt.

Also, I will be pinging here and in slack (our channel) to notify when I am done with writing. Please do proofreading after that.

**Comment by jdeng8** [comment]
OK

**Comment by sshankjha** [comment]
I have added text covering three sections. This is my first draft so I will changing few words and add formatting as well. Let me know if I missed something important. I will finalize the text accordingly later today.

**Comment by MichaelGoff** [comment]
If possible could everyone get their pieces written by 6 or 7pm tonight so I have some time to go through and edit everything?

**Comment by sshankjha** [comment]
@MichaelGoff I am done with my part. Let me know if any changes are required.
Also, I added @bhaskarsinha1311 details at the start of the paper. But we have indentation problem. Any idea how to correct that?

**Comment by bhaskarsinha1311** [comment]
Hey guys, I added a couple of slides to the presentation but it's still coming to 19 slides. Any ideas on what else we can add? So far I have added the following topics:

Problem Statement
How teams are formed now?
Why we chose this topic?
Our Survey
What our surveyors said
Approach One
Approach Two
Approach Three
Conclusion

**Comment by jdeng8** [comment]
How other software deal with this problem?

**Comment by MichaelGoff** [comment]
@sshankjha I have fixed the author problem. There was an alternative format to use for more than 3 authors. 

I will begin reading over and editing. 
@jdeng8 Could you tag me when you complete the remainder of your material so I know when to take another look? Thanks

**Comment by bhaskarsinha1311** [comment]
I have completed a rough draft of the 20 slides. Can you guys review it and give any feedback? 
Also, I have written my understanding of the three approaches, please let me know if it is consistent with what is written in the paper.

**Comment by bhaskarsinha1311** [comment]
https://docs.google.com/presentation/d/1F_SjpHlHEr3xyCYzbyh9EKU_PKQa_HVRNPSRJxi6Tqk/pub?start=false&loop=false&delayms=20000

**Comment by bhaskarsinha1311** [comment]
Thats the published presentation link.

**Comment by jdeng8** [comment]
@bhaskarsinha1311  solution 3 in slides is different from what I described in report. Your words are"the person is in charge of selecting..." But I think the person can not select members. Members bid for projects with different weights according to their preference then a lottery algorithm generates the result.

**Comment by bhaskarsinha1311** [comment]
@jdeng8 Ok I'll rectify that.

**Comment by MichaelGoff** [comment]
Paper complete
